spring:
  security:
    user:
      name: user
      password: 1234


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

dreamSecretKey2006: myDreamSecretKeyItIsEnoughForMe2006!

jwt:
  expiration: 900000
  refresh-expiration: 604800000

