spring:
  security:
    user:
      name: user
      password: 1234

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 60000
      max-lifetime: 18000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        open-in-view: false
        format_sql: true


dreamSecretKey2006: myDreamSecretKeyItIsEnoughForMe2006!

jwt:
  expiration: 900000
  refresh-expiration: 604800000
